name: Build & Test Simplexx

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux-client:
    name: Build Linux Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure build dependencies (only install if missing)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            $(for pkg in build-essential cmake; do dpkg -s $pkg >/dev/null 2>&1 || echo $pkg; done)

      - name: Build Linux client
        working-directory: linux
        run: |
          cmake -B build -S .
          cmake --build build -j$(nproc)

      - name: Archive Linux client
        uses: actions/upload-artifact@v4
        with:
          name: linux-client
          path: linux/build/ghost*

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure cppcheck (only install if missing)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            $(for pkg in cppcheck; do dpkg -s $pkg >/dev/null 2>&1 || echo $pkg; done)

      - name: Run cppcheck
        run: |
          cppcheck --enable=all --inconclusive --std=c++17 --quiet \
            --suppress=missingIncludeSystem --exclude=lib --exclude=build .
            
  build-windows-client:
    name: Build Windows Client
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64, x86]
        os: [windows-latest, self-hosted]
        include:
          - platform: x64
            msvc_arch: x64
            msbuild_platform: x64
          - platform: x86
            msvc_arch: x86
            msbuild_platform: x86
    env:
      CONFIGURATION: ${{ matrix.configuration }}
      PLATFORM: ${{ matrix.platform }}
      MSBUILD_PLATFORM: ${{ matrix.msbuild_platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure Visual Studio Build Tools (only on self-hosted)
        if: runner.os == 'Windows' && runner.name == 'self-hosted'
        shell: powershell
        run: |
          $pkg = choco list --local-only | Select-String "visualstudio2019buildtools"
          if (-not $pkg) {
            choco install visualstudio2019buildtools --package-parameters `
              "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
               --add Microsoft.VisualStudio.Component.Windows10SDK.19041 `
               --add Microsoft.VisualStudio.Component.VC.ATLMFC `
               --add Microsoft.VisualStudio.Component.VC.v142.x86.x64 `
               --add Microsoft.VisualStudio.Component.VC.ATLMFC.v142.x86.x64 `
               --includeRecommended --includeOptional --quiet --norestart" -y
          }

      - name: Setup MSVC dev cmd
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}

      - name: Download zstd source
        shell: powershell
        run: |
          $zstdUrl = "https://github.com/facebook/zstd/releases/download/v1.5.5/zstd-1.5.5-win64.zip"
          $zstdDir = "external\zstd"
          mkdir $zstdDir
          Invoke-WebRequest -Uri $zstdUrl -OutFile "$zstdDir\zstd.zip"
          Expand-Archive -Path "$zstdDir\zstd.zip" -DestinationPath $zstdDir
          Get-ChildItem -Recurse $zstdDir

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution (2019Remote.sln)
        shell: powershell
        run: |
          $sln = (Get-ChildItem -Recurse -Filter '2019Remote.sln' | Select-Object -First 1).FullName
          if (-not $sln) { throw "Solution not found: $sln" }
          & msbuild $sln /m /p:Configuration=$env:CONFIGURATION /p:Platform=$env:MSBUILD_PLATFORM /p:PreferredToolArchitecture=$env:MSBUILD_PLATFORM /p:AdditionalIncludeDirectories="external\zstd\zstd-1.5.5\include"
          if ($LASTEXITCODE -ne 0) { throw "MSBuild failed." }

      - name: Collect artifacts
        shell: powershell
        run: |
          $outDir = "dist\${env:PLATFORM}\${env:CONFIGURATION}"
          New-Item -ItemType Directory -Force -Path $outDir | Out-Null
          $patterns = @('*.exe','*.dll','*.pdb')
          foreach ($pat in $patterns) {
            Get-ChildItem -Recurse -File -Include $pat -Path . | Where-Object {
              $_.DirectoryName -match "\\(x64|x86|Win32)\\$env:CONFIGURATION(\\|$)"
            } | Copy-Item -Destination $outDir -Force -ErrorAction SilentlyContinue
          }
          Get-ChildItem -Recurse $outDir | ForEach-Object { $_.FullName }

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-client-${{ matrix.platform }}-${{ matrix.configuration }}
          path: dist/${{ matrix.platform }}/${{ matrix.configuration }}
          retention-days: 7

  build-documentation:
    name: Build Documentation
    runs-on: [self-hosted, windows]  # Ensure this is using your self-hosted Windows runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            ReadMe.md
            ReadMe_EN.md
            Dependencies.md
            history.md
            使用方法.txt
            使用花生壳.txt
            反向代理.md
          retention-days: 7
